name: Top-search
on:
  push:
    branches:
      - main
  schedule:
    - cron: "* * * * *"

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutss
        uses: actions/checkout@v2

      - name: instpython3
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.1'
      - name: Commit files
        run: |
          git config --local user.email "378600950@qq.com"
          git config --local user.name "qqhsx"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          pip3 install requests
          python hot.py
          git add .
          git commit --allow-empty -m "爬取热点"
          git push -f

          # Add a remote for the other repository and push to it
          git remote add repository_aa https://github.com/qqhsx/aa.git

          git push repository_aa main
