name: Push index.md to qqhsx/aa

on:
  push:
    branches:
      - main # 或者你要监控的分支，根据实际情况进行调整

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create target directory
        run: mkdir -p aa/

      - name: Copy index.md to qqhsx/aa
        run: cp index.md aa/index.md

      - name: Commit and push
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          git add aa/index.md
          git commit -m "Update index.md"
          git push origin main
