name: Copy Index File

on:
  push:
    branches:
      - main  # 触发分支，可以根据需要更改

jobs:
  copy_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Top-search Repository
      uses: actions/checkout@v2
      with:
        repository: qqhsx/Top-search
        ref: main  # 源仓库分支

    - name: Copy Index File
      run: |
        cp index.md $GITHUB_WORKSPACE/aa/
      working-directory: .

    - name: Commit and Push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git clone https://github.com/qqhsx/aa.git
        cd aa
        mv ../index.md ./
        git add index.md
        git commit -m "Copy index.md"
        git push
      working-directory: .
