name: Copy Index File

on:
  push:
    branches:
      - main  # 触发分支，可以根据需要更改

jobs:
  copy_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Top-search Repository
      uses: actions/checkout@v2
      with:
        repository: qqhsx/Top-search
        ref: main  # 源仓库分支

    - name: Copy Index File
      run: |
        mkdir -p ../aa  # 创建目标目录，如果不存在
        cp index.md ../aa/
      working-directory: ./qqhsx/Top-search  # 源仓库路径

    - name: Commit and Push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add ../aa/index.md
        git commit -m "Copy index.md"
        git push
      working-directory: ./qqhsx/Top-search  # 源仓库路径

