name: Push index.md to qqhsx/aa

on:
  push:
    branches:
      - main # 或者你要监控的分支，根据实际情况进行调整

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload index.md to qqhsx/aa
        run: |
          curl -X PUT "https://api.github.com/repos/qqhsx/aa/contents/index.md" \
          -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -d '{
            "message": "Update index.md",
            "content": "'"$(base64 -w0 index.md)"'"
          }'

