name: Push index.md to qqhsx/aa

on:
  push:
    branches:
      - main # 或者你要监控的分支，根据实际情况进行调整

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone target repository
        run: |
          git clone https://github.com/qqhsx/aa.git
          cp index.md aa/index.md
          cd aa
          git config --local user.email "actions@example.com"
          git config --local user.name "GitHub Actions"
          git add index.md
          git commit -m "Update index.md"
          git push origin main
